title: Guilherme D'Almeida
logo: /assets/imgs/guilherme.jpg
description: A 25 year-old who went his impact passion for 3 years and is now ready to apply it to the grind of programming.
theme: jekyll-theme-minimal
