title: Guilherme D'Almeida
logo: /assets/imgs/guilherme.jpg
description: A 25 year-old who went after soft-skills for 3 years and is now ready to comeback to the grind of programming.
theme: jekyll-theme-minimal
